---
- hosts: front
  become: true

  vars:
    wp_db_pass: bob

  tasks:
    # avec le module apt et une boucle with_items, installer les packages:
    # apache2, wordpress et mysql-client
    #
    # http://docs.ansible.com/ansible/apt_module.html
    # http://docs.ansible.com/ansible/playbooks_loops.html#standard-loops

    # avec le module service, s'assurer que le service apache2 est:
    # démarré, activé au boot
    #
    # http://docs.ansible.com/ansible/service_module.html

    - name: apache site configuration
      copy:
        src=files/wordpress.apache2.conf
        dest=/etc/apache2/sites-available/default-wp.conf
        owner=root
        group=root
        mode=0644
      notify: enable apache site

    - name: wordpress configuration
      template:
        src=templates/wordpress.etc.conf.j2
        dest=/etc/wordpress/config-default.php
        owner=root
        group=www-data
        mode=0640

    # utiliser une boucle with_items pour factoriser les 2 prochaines tasks
    #
    # http://docs.ansible.com/ansible/playbooks_loops.html#standard-loops

    - name: REFACTOR wordpress content has correct ownership
      file:
        path='/var/lib/wordpress/wp-content'
        state=directory
        owner=www-data
        group=www-data
        recurse=yes

    - name: REFACTOR wordpress content has correct ownership
      file:
        path='/usr/share/wordpress/wp-content'
        state=directory
        owner=www-data
        group=www-data
        recurse=yes


    - name: Rewrite module activated
      apache2_module:
        name=rewrite
        state=present

  handlers:
    - name: enable apache site
      shell: /usr/sbin/a2dissite 000-default && /usr/sbin/a2ensite default-wp
      notify: restart apache

    - name: restart apache
      service:
        name=apache2
        state=restarted

- hosts: back
  become: true
  vars:
    wp_db_pass: bob
  tasks:
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - mysql-server
        - python-mysqldb

    # avec le module mysql_db, s'assurer qu'une base nommé wordpress existe
    #
    # http://docs.ansible.com/ansible/mysql_db_module.html

    - name: mysql user is created
      mysql_user:
        name=wordpress
        host="{{ groups['front'][0] }}"
        password="{{ wp_db_pass }}"
        priv="wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state=present

    # avec le module lineinfile, s'assurer que dans le fichier /etc/mysql/my.cnf
    # la ligne qui commence par 'bind-address' vaut:
    # "bind-address = {{ ansible_default_ipv4.address }}"
    #
    # notifié le handler "restart db"
    #
    # http://docs.ansible.com/ansible/lineinfile_module.html

    - name: db enabled
      service:
        name=mysql
        state=started
        enabled=yes

  handlers:
    - name: restart db
      service:
        name=mysql
        state=restarted
        enabled=yes

