---
- hosts: front
  become: true

  vars:
    wp_db_pass: bob

  tasks:
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - apache2
        - mysql-client
        - wordpress

    - name: apache service started
      service:
        name=apache2
        state=started
        enabled=yes

    - name: apache site configuration
      copy:
        src=files/wordpress.apache2.conf
        dest=/etc/apache2/sites-available/default-wp.conf
        owner=root
        group=root
        mode=0644
      notify: enable apache site

    - name: wordpress configuration
      template:
        src=templates/wordpress.etc.conf.j2
        dest=/etc/wordpress/config-default.php
        owner=root
        group=www-data
        mode=0640

    - name: wordpress content has correct ownership
      file:
        path="{{ item }}"
        state=directory
        owner=www-data
        group=www-data
        recurse=yes
      with_items:
        - /var/lib/wordpress/wp-content
        - /usr/share/wordpress/wp-content

    - name: Rewrite module activated
      apache2_module:
        name=rewrite
        state=present

  handlers:
    - name: enable apache site
      shell: /usr/sbin/a2dissite 000-default && /usr/sbin/a2ensite default-wp
      notify: restart apache

    - name: restart apache
      service:
        name=apache2
        state=restarted

- hosts: back
  become: true
  vars:
    wp_db_pass: bob
  tasks:
    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - mysql-server
        - python-mysqldb

    - name: mysql database is created
      mysql_db:
        name=wordpress
        state=present

    - name: mysql user is created
      mysql_user:
        name=wordpress
        host="{{ groups['front'][0] }}"
        password="{{ wp_db_pass }}"
        priv="wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state=present

    - lineinfile:
        dest=/etc/mysql/my.cnf
        regexp='^bind-address.*$'
        line="bind-address = {{ ansible_default_ipv4.address }}"
      notify: restart db

    - name: db enabled
      service:
        name=mysql
        state=started
        enabled=yes

  handlers:
    - name: restart db
      service:
        name=mysql
        state=restarted
        enabled=yes

