---
- name: ansible_local Quick Start
  hosts: all
  user: ubuntu
  become: true

  tasks:
    - name: packages installed
      apt: 
        pkg={{ item }}
        state=present	  
      with_items: 
        - apache2
        - mysql-client
        - php5

    - name: Apache start
      service: name=apache2 state=started 
