---

- name: common alias
  copy:
    dest=/etc/profile.d/ll.sh
    content="alias ll=\"ls --color -aul\"\n"
    owner=root
    group=root
    mode=0644

- name: /bin/sh is /bin/bash
  file:
    src=/bin/bash
    dest=/bin/sh
    state=link

- name: goaccess apt repository key is trusted
  apt_key:
    url=http://deb.goaccess.io/gnugpg.key
    state=present

- name: goaccess apt repository is active
  apt_repository:
    repo="deb http://deb.goaccess.io {{ ansible_distribution_release }} main"
    state=present
    update_cache=yes

- name: backports repositories are actives
  apt_repository:
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - "deb http://cloudfront.debian.net/debian {{ ansible_distribution_release }}-backports main"
    - "deb-src http://cloudfront.debian.net/debian {{ ansible_distribution_release }}-backports main"

- name: common packages are installed
  apt:
    pkg="{{ item }}"
    state=present
  with_items:
    - mosh
    - sudo
    - curl
    - locales
    - git
    - subversion
    - whois
    - wget
    - strace
    - sysstat
    - iotop
    - iperf
    - lsof
    - dnsutils
    - ngrep
    - htop
    - netcat
    - multitail
    - tmux
    - tree
    - ncdu
    - net-tools
    - procps
    - goaccess
    - vim
    - jq
    - zabbix-agent
    - htop
    - rsyslog
    - logrotate
    - unattended-upgrades
    - build-essential
    - zlib1g-dev
    - zlib1g
    - libcurl4-openssl-dev

- name: common packages are installed
  apt:
    pkg="{{ item }}"
    state=present
  with_items:
    - dhcpcd
  when: ansible_distribution_release == 'wheezy'

- name: common python libraries and tools are installed
  pip:
    name="{{ item }}"
    state=latest
  with_items:
    - botocore
    - boto
    - awscli

- name: fix DHCPD static route (only for wheezy, Jessie is clean)
  lineinfile:
    dest="/etc/default/dhcpcd"
    regexp="^OPTIONS=.*"
    line="OPTIONS=(-L)"
    backup=yes
  when: ansible_distribution_release == 'wheezy'

- include: ntp.yml
- include: locale.yml
- include: ssh.yml
- include: logs.yml