---
- hosts: front_and_back
  become: yes

# definir la variable avec le chemin complet vers votre lé publique
  vars:
    public_key_path=""

  tasks:
    - user:
        name=ansible

    - file:
        path=/home/ansible/.ssh
        state=directory
        owner=ansible
        group=ansible
        mode=0700

    - authorized_key:
        user: ansible
        key: "{{ lookup('file', public_key_path) }}"

    - name: service_user is sudoer
      lineinfile: >
        dest=/etc/sudoers.d/service_user
        regexp='^{{ service_user }}'
        line='{{ service_user }} ALL=(ALL) NOPASSWD: ALL'
        state='present'
        validate='visudo -cf %s'
        create=yes

    - name: service_user is sudo without tty
      lineinfile: >
        dest=/etc/sudoers.d/service_user
        regexp='^Defaults:{{ service_user }}'
        line='Defaults:{{ service_user }} !requiretty'
        state='present'
        validate='visudo -cf %s'
        create=yes

